name: up
on: push
permissions:
  contents: write
jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: upload
        run: gh release upload julie-v23-raw-sources files/* --repo ${{ github.repository }} --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
